name: build and deploy code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build_and_test
    env:
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
      JWT_TOKEN_EXPIRE_MINUTES: ${{secrets.JWT_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retires 5

    steps:
      - name: pull git repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install dependencies
        run: pip install -r requirements.txt -q

      - name: run pytest
        run: |
          pip install pytest
          pytest
